### ISSUE TITLE
No messages in telegram of Slack bot (newbie issues)

### ISSUE THREAD

**Issue by andreiasil94** [orangecoding/fredy#107]
I am very new in this world. I am just a PhD student trying to find a apartment in Berlin. Since my chances are very low I was trying to use your code, that you kindly provided. However, it is my first time using such bots or Docker and I thing I am doing something wrong because I do not received any messages in the bot I created in telegram and slack even though in Fredy page shows some findings. What should I do to implement these bots in Fredy? I tried to follow your instructions but it is too advance for me to understand what I did wrong. When I used TRY in the provider it says it works.

**Comment by orangecoding** [comment]
Hey. Sorry for coming back to you late. Do you see any errors/problems in the logs?

Have you checked if Fredy actually find something?

**Comment by andreiasil94** [comment]
Hi. Yes, logs show errors like this one:
Error: invalid_auth
2024-09-02 08:11:30     at Object.exec (/fredy/node_modules/slack/src/_exec.js:11:15)
2024-09-02 08:11:30     at file:///fredy/lib/notification/adapter/slack.js:7:5
2024-09-02 08:11:30     at Array.map (<anonymous>)
2024-09-02 08:11:30     at Module.send (file:///fredy/lib/notification/adapter/slack.js:6:22)
2024-09-02 08:11:30     at file:///fredy/lib/notification/notify.js:23:19
2024-09-02 08:11:30     at Array.map (<anonymous>)
2024-09-02 08:11:30     at Module.send (file:///fredy/lib/notification/notify.js:23:6)
2024-09-02 08:11:30     at FredyRuntime._notify (file:///fredy/lib/FredyRuntime.js:103:38)
2024-09-02 08:11:30     at async file:///fredy/index.js:38:15

Fredy is finding offers, but the problem is that I do not get any notifications in the bot that I created for telegram and Slack.

**Comment by orangecoding** [comment]
It says 'invalid auth' that means the authentication did not work properly. Are you sure you are using the correct credentials?
